ABU_FACULTY_DEPARTMENTS: dict[str, list[str]] = {
    "ABU Business School": [
        "Accounting",
        "Actuarial Science & Insurance",
        "Banking and Finance",
        "Business Administration",
        "Economics",
        "Marketing",
    ],
    "Administration": [
        "Accounting",
        "Actuarial Science",
        "Banking and Finance",
        "Business Administration",
        "Insurance",
        "Local Government and Development Studies",
        "Public Administration",
    ],
    "Agriculture": [
        "Agricultural Economics",
        "Agricultural Extension and Rural Development",
        "Agronomy",
        "Animal Science",
        "Crop Protection",
        "Plant Science",
        "Soil Science",
    ],
    "Allied Health Sciences": [
        "Medical Laboratory Science",
        "Nursing Science",
        "Physiotherapy",
        "Radiography",
    ],
    "Arts": [
        "African Languages and Cultures",
        "Arabic",
        "English and Literary Studies",
        "French",
        "History",
        "Linguistics",
        "Theatre and Performing Arts",
    ],
    "Basic Clinical Sciences": [],
    "Basic Medical Sciences": [
        "Anatomy",
        "Medical Biochemistry",
        "Physiology",
    ],
    "Dental Surgery": [],
    "Clinical Sciences": [],
    "Education": [
        "Arts and Social Science Education",
        "Educational Foundations and Curriculum",
        "Educational Psychology and Counselling",
        "Physical and Health Education",
        "Science Education",
        "Vocational and Technical Education",
    ],
    "Engineering": [
        "Agricultural and Bio-Resources Engineering",
        "Automotive Engineering",
        "Chemical Engineering",
        "Civil Engineering",
        "Computer Engineering",
        "Electrical Engineering",
        "Mechanical Engineering",
        "Mechatronics Engineering",
        "Metallurgical and Materials Engineering",
        "Mining Engineering",
        "Telecommunication Engineering",
        "Water Resources and Environmental Engineering",
    ],
    "Environmental Design": [
        "Architecture",
        "Building",
        "Industrial Design",
        "Quantity Surveying",
        "Surveying and Geoinformatics",
        "Urban and Regional Planning",
    ],
    "Law": [
        "Commercial Law",
        "Islamic Law",
        "Private Law",
        "Public Law",
    ],
    "Life Sciences": [
        "Botany",
        "Microbiology",
        "Zoology",
    ],
    "Physical Sciences": [
        "Chemistry",
        "Computer Science",
        "Geology",
        "Mathematics",
        "Physics",
        "Statistics",
    ],
    "Pharmacy": [
        "Clinical Pharmacy and Pharmacy Practice",
        "Pharmaceutical Chemistry",
        "Pharmaceutical Microbiology",
        "Pharmaceutics and Pharmaceutical Technology",
        "Pharmacognosy and Drug Development",
        "Pharmacology and Therapeutics",
    ],
    "Social Sciences": [
        "Economics",
        "Geography",
        "Mass Communication",
        "Political Science and International Studies",
        "Sociology",
    ],
    "Veterinary Medicine": [
        "Veterinary Medicine",
        "Veterinary Anatomy",
        "Veterinary Microbiology",
        "Veterinary Parasitology and Entomology",
        "Veterinary Pathology",
        "Veterinary Pharmacology and Toxicology",
        "Veterinary Physiology",
        "Veterinary Public Health and Preventive Medicine",
        "Veterinary Surgery and Radiology",
    ],
}

